#!/usr/bin/env bash
#
# sync-env.sh - project agents.conf into the .env vars docker compose reads.
#
# agents.conf is the source of truth for the agent setup, but docker compose only
# interpolates from .env. Without this bridge, compose silently falls back to the
# template defaults (./vault, vault_home, ...) while hermes.sh seeds the real
# folders from agents.conf - so n8n watches an empty directory, the indexers index
# nothing, and handoffs never fire.
#
#   ./scripts/sync-env.sh            # print the derived block (dry run)
#   ./scripts/sync-env.sh --write    # rewrite the managed block in .env (idempotent)
#
# Re-run it after every agents.conf change, then recreate the affected services:
#   docker compose --profile prod --profile home up -d
#
# Everything it emits is derived config, never a secret. Secrets stay in .env,
# hand-written, outside the managed block.

set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

if [ -f "$ROOT/agents.conf" ]; then
	# shellcheck disable=SC1091
	source "$ROOT/agents.conf"
elif [ -f "$ROOT/agents.conf.example" ]; then
	# shellcheck disable=SC1091
	source "$ROOT/agents.conf.example"
else
	echo "no agents.conf found" >&2
	exit 1
fi

ASSISTANT_NAME="${ASSISTANT_NAME:-assistant}"
ASSISTANT_MODEL="${ASSISTANT_MODEL:-deepseek/deepseek-v2-flash}"
ASSISTANT_FOLDER="${ASSISTANT_FOLDER:-scratchpads}"
ASSISTANT_PORT="${ASSISTANT_PORT:-8642}"

ENGINEER_NAME="${ENGINEER_NAME:-engineer}"
ENGINEER_MODEL="${ENGINEER_MODEL:-anthropic/claude-opus-4-8}"
ENGINEER_FOLDER="${ENGINEER_FOLDER:-projects}"
ENGINEER_PORT="${ENGINEER_PORT:-8643}"

RESEARCHER_NAME="${RESEARCHER_NAME:-researcher}"
RESEARCHER_MODEL="${RESEARCHER_MODEL:-z-ai/glm-4.6}"
RESEARCHER_FOLDER="${RESEARCHER_FOLDER:-memory}"
RESEARCHER_PORT="${RESEARCHER_PORT:-8644}"

PRIMARY_VAULT="${PRIMARY_VAULT:-vault}"
PRIMARY_COLLECTION="${PRIMARY_COLLECTION:-vault}"
HOME_VAULT="${HOME_VAULT:-vault-home}"
HOME_COLLECTION="${HOME_COLLECTION:-vault_home}"

# Keyword triage, used only by router.json's webhook front door. The assistant is
# the fallback, so it needs no match.
ENGINEER_MATCH="${ENGINEER_MATCH:-build|code|ngoding|implement|refactor|debug|bug|deploy}"
RESEARCHER_MATCH="${RESEARCHER_MATCH:-research|cari|riset|investigate|find out|literature}"

# One line, no spaces after separators: consumed from .env, where stray quoting
# would corrupt it. The home agent is deliberately absent - it is isolated and
# n8n never routes to it.
ROUTES=$(printf '{"%s":{"port":%s,"model":"%s","folder":"%s","default":true},"%s":{"port":%s,"model":"%s","folder":"%s","match":"%s"},"%s":{"port":%s,"model":"%s","folder":"%s","match":"%s"}}' \
	"$ASSISTANT_NAME" "$ASSISTANT_PORT" "$ASSISTANT_MODEL" "$ASSISTANT_FOLDER" \
	"$ENGINEER_NAME" "$ENGINEER_PORT" "$ENGINEER_MODEL" "$ENGINEER_FOLDER" "$ENGINEER_MATCH" \
	"$RESEARCHER_NAME" "$RESEARCHER_PORT" "$RESEARCHER_MODEL" "$RESEARCHER_FOLDER" "$RESEARCHER_MATCH")

BEGIN="# >>> generated by scripts/sync-env.sh - do not edit by hand >>>"
END="# <<< generated by scripts/sync-env.sh <<<"

block() {
	printf '%s\n' "$BEGIN"
	printf 'PRIMARY_VAULT=%s\n' "$PRIMARY_VAULT"
	printf 'PRIMARY_COLLECTION=%s\n' "$PRIMARY_COLLECTION"
	printf 'HOME_VAULT=%s\n' "$HOME_VAULT"
	printf 'HOME_COLLECTION=%s\n' "$HOME_COLLECTION"
	printf 'GHIATH_ROUTES=%s\n' "$ROUTES"
	printf '%s\n' "$END"
}

if [ "${1:-}" != "--write" ]; then
	block
	echo
	echo "# dry run. Apply with: ./scripts/sync-env.sh --write" >&2
	exit 0
fi

[ -f .env ] || { echo ".env not found" >&2; exit 1; }
cp .env .env.bak

# Drop any previous managed block, plus bare copies of the keys we own (e.g. a
# GHIATH_ROUTES appended by hand), so re-running can never leave a stale duplicate
# that shadows the fresh value.
awk -v b="$BEGIN" -v e="$END" '
	$0 == b { skip = 1; next }
	$0 == e { skip = 0; next }
	skip { next }
	/^(PRIMARY_VAULT|PRIMARY_COLLECTION|HOME_VAULT|HOME_COLLECTION|GHIATH_ROUTES)=/ { next }
	{ print }
' .env.bak > .env

# Keep exactly one blank line before the block.
[ -s .env ] && [ -n "$(tail -c1 .env)" ] && printf '\n' >> .env
block >> .env

echo "[sync-env] .env updated (backup: .env.bak)"
echo "[sync-env] primary vault: $PRIMARY_VAULT -> collection $PRIMARY_COLLECTION"
echo "[sync-env] home vault:    $HOME_VAULT -> collection $HOME_COLLECTION"
echo "[sync-env] routes:        $ASSISTANT_NAME(default) $ENGINEER_NAME $RESEARCHER_NAME"
