#!/usr/bin/env bash
#
# sync-env.sh - project agents.conf into the .env vars docker compose reads.
#
# agents.conf is the source of truth for the agent setup, but docker compose only
# interpolates from .env. Without this bridge, compose silently falls back to the
# template defaults while hermes.sh seeds the real folders from agents.conf - so
# the indexers index nothing and the LiveSync bridge watches an empty directory.
#
#   ./scripts/sync-env.sh            # print the derived block (dry run)
#   ./scripts/sync-env.sh --write    # rewrite the managed block in .env (idempotent)
#
# Re-run it after every agents.conf change, then recreate the affected services:
#   docker compose up -d
#
# Everything it emits is derived config, never a secret. Secrets stay in .env,
# hand-written, outside the managed block.

set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

if [ -f "$ROOT/agents.conf" ]; then
	# shellcheck disable=SC1091
	source "$ROOT/agents.conf"
elif [ -f "$ROOT/agents.conf.example" ]; then
	# shellcheck disable=SC1091
	source "$ROOT/agents.conf.example"
else
	echo "no agents.conf found" >&2
	exit 1
fi

# See the matching guard in hermes.sh: a stale three-agent agents.conf would
# otherwise make compose mount the neutral default folders instead of the real
# vaults, and the indexers would quietly index nothing.
if [ -z "${WORK_VAULT:-}" ] && [ -n "${PRIMARY_VAULT:-}${ASSISTANT_NAME:-}" ]; then
	echo "ERROR: agents.conf is still in the old three-agent format (PRIMARY_*/ASSISTANT_*)." >&2
	echo "       Rewrite it with WORK_* and HOME_* first; see agents.conf.example." >&2
	echo "       Run ./scripts/hermes.sh for the full migration snippet." >&2
	exit 1
fi

WORK_VAULT="${WORK_VAULT:-vault-work}"
WORK_COLLECTION="${WORK_COLLECTION:-vault_work}"
HOME_VAULT="${HOME_VAULT:-vault-home}"
HOME_COLLECTION="${HOME_COLLECTION:-vault_home}"

BEGIN="# >>> generated by scripts/sync-env.sh - do not edit by hand >>>"
END="# <<< generated by scripts/sync-env.sh <<<"

block() {
	printf '%s\n' "$BEGIN"
	printf 'WORK_VAULT=%s\n' "$WORK_VAULT"
	printf 'WORK_COLLECTION=%s\n' "$WORK_COLLECTION"
	printf 'HOME_VAULT=%s\n' "$HOME_VAULT"
	printf 'HOME_COLLECTION=%s\n' "$HOME_COLLECTION"
	printf '%s\n' "$END"
}

if [ "${1:-}" != "--write" ]; then
	block
	echo
	echo "# dry run. Apply with: ./scripts/sync-env.sh --write" >&2
	exit 0
fi

[ -f .env ] || { echo ".env not found" >&2; exit 1; }
cp .env .env.bak

# Drop any previous managed block, plus bare copies of the keys we own, so
# re-running can never leave a stale duplicate that shadows the fresh value.
# PRIMARY_* and GHIATH_ROUTES are the retired names from the three-agent setup;
# they are stripped so a stale value cannot point compose at the wrong folder.
awk -v b="$BEGIN" -v e="$END" '
	$0 == b { skip = 1; next }
	$0 == e { skip = 0; next }
	skip { next }
	/^(WORK_VAULT|WORK_COLLECTION|HOME_VAULT|HOME_COLLECTION)=/ { next }
	/^(PRIMARY_VAULT|PRIMARY_COLLECTION|GHIATH_ROUTES)=/ { next }
	{ print }
' .env.bak > .env

# Keep exactly one blank line before the block.
[ -s .env ] && [ -n "$(tail -c1 .env)" ] && printf '\n' >> .env
block >> .env

echo "[sync-env] .env updated (backup: .env.bak)"
echo "[sync-env] work vault: $WORK_VAULT -> collection $WORK_COLLECTION"
echo "[sync-env] home vault: $HOME_VAULT -> collection $HOME_COLLECTION"

# --- livesync-bridge config -------------------------------------------------
# Pairs each vault directory with a CouchDB database under a shared "group", so
# the notes the agents write on disk reach your devices, and vice versa. Holds the
# CouchDB password, so it is generated into a gitignored file rather than committed.
#
# The database names are what you type into the Obsidian LiveSync plugin. Keep
# them stable: changing a database name here orphans everything already synced
# under the old name. The passphrase must match the plugin's E2EE passphrase, or
# the two cannot read each other; leave it empty on both sides to keep E2EE off.
# '|| true': a missing key is normal (the defaults below cover it), but grep exits
# 1 on no match and set -o pipefail would otherwise abort the whole script.
getenv() { { grep -E "^$1=" .env || true; } | head -n1 | cut -d= -f2- | sed -e "s/^['\"]//" -e "s/['\"]\$//"; }
COUCHDB_USER="$(getenv COUCHDB_USER)"
COUCHDB_PASSWORD="$(getenv COUCHDB_PASSWORD)"
LIVESYNC_DB="$(getenv LIVESYNC_DB)"; LIVESYNC_DB="${LIVESYNC_DB:-ghiath}"
LIVESYNC_HOME_DB="$(getenv LIVESYNC_HOME_DB)"; LIVESYNC_HOME_DB="${LIVESYNC_HOME_DB:-ghiath-home}"
LIVESYNC_PASSPHRASE="$(getenv LIVESYNC_PASSPHRASE)"

mkdir -p livesync-bridge
COUCHDB_USER="$COUCHDB_USER" COUCHDB_PASSWORD="$COUCHDB_PASSWORD" \
LIVESYNC_DB="$LIVESYNC_DB" LIVESYNC_HOME_DB="$LIVESYNC_HOME_DB" \
LIVESYNC_PASSPHRASE="$LIVESYNC_PASSPHRASE" \
WORK_VAULT="$WORK_VAULT" HOME_VAULT="$HOME_VAULT" \
python3 - <<'PY' > livesync-bridge/config.json
import json, os

def couch(name, group, database):
    peer = {
        "type": "couchdb",
        "name": name,
        "group": group,
        "database": database,
        # Inside the compose network, not via Caddy: no TLS hop, no public exposure.
        "url": "http://couchdb:5984",
        "username": os.environ["COUCHDB_USER"],
        "password": os.environ["COUCHDB_PASSWORD"],
        # Required, not optional: the peer joins it into every path, and a missing
        # baseDir crashes the watcher with 'Path must be a string, received
        # "undefined"'. Empty string = sync the whole vault, not a subfolder.
        "baseDir": "",
    }
    if os.environ.get("LIVESYNC_PASSPHRASE"):
        peer["passphrase"] = os.environ["LIVESYNC_PASSPHRASE"]
    return peer

def storage(name, group, vault):
    # baseDir must sit under data/ - that is what the bridge mounts.
    return {
        "type": "storage",
        "name": name,
        "group": group,
        "baseDir": f"./data/{vault}/",
        # Pick up notes written while the bridge was down (e.g. by an agent).
        "scanOfflineChanges": True,
    }

# Two groups, never crossed: the household devices sync the home vault and can
# never see the work one, because they are separate CouchDB databases.
peers = [
    couch("work-remote", "work", os.environ["LIVESYNC_DB"]),
    storage("work-vault", "work", os.environ["WORK_VAULT"]),
    couch("home-remote", "home", os.environ["LIVESYNC_HOME_DB"]),
    storage("home-vault", "home", os.environ["HOME_VAULT"]),
]

print(json.dumps({"peers": peers}, indent=2))
PY

echo "[sync-env] livesync-bridge/config.json written"
echo "[sync-env]   $WORK_VAULT <-> couchdb db '$LIVESYNC_DB'"
echo "[sync-env]   $HOME_VAULT <-> couchdb db '$LIVESYNC_HOME_DB'"
if [ -z "$LIVESYNC_PASSPHRASE" ]; then
	echo "[sync-env]   E2EE off (set LIVESYNC_PASSPHRASE in .env to enable; must match Obsidian)"
fi
